pull_request_rules:
  - name: Assign author to review conflict and add label of 'conflict'
    conditions:
      - conflict
    actions:
      label:
        add:
          - conflict
      assign:
        add_users:
          - aakvatech
          - "{{author}}"
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
  
  - name: Automatic merge after review to version-13-hotfix
    conditions:
      - base = version-13-hotfix
      - label != conflict
      - "#approved-reviews-by >= 1"

  - name: Automatic merge pull request to version-13
    conditions:
      - and:
          - and:
              - base = version-13
              - label != conflict
          - or:
              - author = aakvatech
              - author = av-dev2
    actions:
      merge:
        method: merge
  